<?php
/**
 * UnifiedAutomationSetting
 * CampaignManagementService
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Microsoft\MsAds\Rest\Model\CampaignManagementService
 * @author   Microsoft Advertising
 */

namespace Microsoft\MsAds\Rest\Model\CampaignManagementService;

use ArrayAccess;
use Microsoft\MsAds\Rest\ObjectSerializer;
use Microsoft\MsAds\Rest\ModelInterface;

class UnifiedAutomationSetting extends Setting implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'UnifiedAutomationSetting';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static array $openAPITypes = [
        'Type' => 'string',
        'ChannelOptimizationOptOut' => 'bool',
        'AudienceOptimizationOptOut' => 'bool',
        'FinalUrlExpansionOptOut' => 'bool',
        'AutoGeneratedTextOptOut' => 'bool',
        'AutoGeneratedImageOptOut' => 'bool',
        'SearchTermMatchingOptOut' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'Type' => null,
        'ChannelOptimizationOptOut' => null,
        'AudienceOptimizationOptOut' => null,
        'FinalUrlExpansionOptOut' => null,
        'AutoGeneratedTextOptOut' => null,
        'AutoGeneratedImageOptOut' => null,
        'SearchTermMatchingOptOut' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'Type' => true,
        'ChannelOptimizationOptOut' => true,
        'AudienceOptimizationOptOut' => true,
        'FinalUrlExpansionOptOut' => true,
        'AutoGeneratedTextOptOut' => true,
        'AutoGeneratedImageOptOut' => true,
        'SearchTermMatchingOptOut' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'Type' => 'Type',
        'ChannelOptimizationOptOut' => 'ChannelOptimizationOptOut',
        'AudienceOptimizationOptOut' => 'AudienceOptimizationOptOut',
        'FinalUrlExpansionOptOut' => 'FinalUrlExpansionOptOut',
        'AutoGeneratedTextOptOut' => 'AutoGeneratedTextOptOut',
        'AutoGeneratedImageOptOut' => 'AutoGeneratedImageOptOut',
        'SearchTermMatchingOptOut' => 'SearchTermMatchingOptOut'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static array $setters = [
        'Type' => 'setType',
        'ChannelOptimizationOptOut' => 'setChannelOptimizationOptOut',
        'AudienceOptimizationOptOut' => 'setAudienceOptimizationOptOut',
        'FinalUrlExpansionOptOut' => 'setFinalUrlExpansionOptOut',
        'AutoGeneratedTextOptOut' => 'setAutoGeneratedTextOptOut',
        'AutoGeneratedImageOptOut' => 'setAutoGeneratedImageOptOut',
        'SearchTermMatchingOptOut' => 'setSearchTermMatchingOptOut'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static array $getters = [
        'Type' => 'getType',
        'ChannelOptimizationOptOut' => 'getChannelOptimizationOptOut',
        'AudienceOptimizationOptOut' => 'getAudienceOptimizationOptOut',
        'FinalUrlExpansionOptOut' => 'getFinalUrlExpansionOptOut',
        'AutoGeneratedTextOptOut' => 'getAutoGeneratedTextOptOut',
        'AutoGeneratedImageOptOut' => 'getAutoGeneratedImageOptOut',
        'SearchTermMatchingOptOut' => 'getSearchTermMatchingOptOut'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('Type', $data ?? [], null);
        $this->setIfExists('ChannelOptimizationOptOut', $data ?? [], null);
        $this->setIfExists('AudienceOptimizationOptOut', $data ?? [], null);
        $this->setIfExists('FinalUrlExpansionOptOut', $data ?? [], null);
        $this->setIfExists('AutoGeneratedTextOptOut', $data ?? [], null);
        $this->setIfExists('AutoGeneratedImageOptOut', $data ?? [], null);
        $this->setIfExists('SearchTermMatchingOptOut', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets Type
     *
     * @return string|null
     */
    public function getType()
    {
        if (!isset($this->container['Type']) || is_null($this->container['Type'])) {
            return null;
        }
        return $this->container['Type'];
    }

    /**
     * Sets Type
     *
     * @param string|null $Type Type
     *
     * @return self
     */
    public function setType($Type)
    {
        if (is_null($Type)) {
            array_push($this->openAPINullablesSetToNull, 'Type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('Type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['Type'] = $Type;

        return $this;
    }

    /**
     * Gets ChannelOptimizationOptOut
     *
     * @return bool|null
     */
    public function getChannelOptimizationOptOut()
    {
        if (!isset($this->container['ChannelOptimizationOptOut']) || is_null($this->container['ChannelOptimizationOptOut'])) {
            return null;
        }
        return $this->container['ChannelOptimizationOptOut'];
    }

    /**
     * Sets ChannelOptimizationOptOut
     *
     * @param bool|null $ChannelOptimizationOptOut ChannelOptimizationOptOut
     *
     * @return self
     */
    public function setChannelOptimizationOptOut($ChannelOptimizationOptOut)
    {
        if (is_null($ChannelOptimizationOptOut)) {
            array_push($this->openAPINullablesSetToNull, 'ChannelOptimizationOptOut');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ChannelOptimizationOptOut', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ChannelOptimizationOptOut'] = $ChannelOptimizationOptOut;

        return $this;
    }

    /**
     * Gets AudienceOptimizationOptOut
     *
     * @return bool|null
     */
    public function getAudienceOptimizationOptOut()
    {
        if (!isset($this->container['AudienceOptimizationOptOut']) || is_null($this->container['AudienceOptimizationOptOut'])) {
            return null;
        }
        return $this->container['AudienceOptimizationOptOut'];
    }

    /**
     * Sets AudienceOptimizationOptOut
     *
     * @param bool|null $AudienceOptimizationOptOut AudienceOptimizationOptOut
     *
     * @return self
     */
    public function setAudienceOptimizationOptOut($AudienceOptimizationOptOut)
    {
        if (is_null($AudienceOptimizationOptOut)) {
            array_push($this->openAPINullablesSetToNull, 'AudienceOptimizationOptOut');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('AudienceOptimizationOptOut', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['AudienceOptimizationOptOut'] = $AudienceOptimizationOptOut;

        return $this;
    }

    /**
     * Gets FinalUrlExpansionOptOut
     *
     * @return bool|null
     */
    public function getFinalUrlExpansionOptOut()
    {
        if (!isset($this->container['FinalUrlExpansionOptOut']) || is_null($this->container['FinalUrlExpansionOptOut'])) {
            return null;
        }
        return $this->container['FinalUrlExpansionOptOut'];
    }

    /**
     * Sets FinalUrlExpansionOptOut
     *
     * @param bool|null $FinalUrlExpansionOptOut FinalUrlExpansionOptOut
     *
     * @return self
     */
    public function setFinalUrlExpansionOptOut($FinalUrlExpansionOptOut)
    {
        if (is_null($FinalUrlExpansionOptOut)) {
            array_push($this->openAPINullablesSetToNull, 'FinalUrlExpansionOptOut');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('FinalUrlExpansionOptOut', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['FinalUrlExpansionOptOut'] = $FinalUrlExpansionOptOut;

        return $this;
    }

    /**
     * Gets AutoGeneratedTextOptOut
     *
     * @return bool|null
     */
    public function getAutoGeneratedTextOptOut()
    {
        if (!isset($this->container['AutoGeneratedTextOptOut']) || is_null($this->container['AutoGeneratedTextOptOut'])) {
            return null;
        }
        return $this->container['AutoGeneratedTextOptOut'];
    }

    /**
     * Sets AutoGeneratedTextOptOut
     *
     * @param bool|null $AutoGeneratedTextOptOut AutoGeneratedTextOptOut
     *
     * @return self
     */
    public function setAutoGeneratedTextOptOut($AutoGeneratedTextOptOut)
    {
        if (is_null($AutoGeneratedTextOptOut)) {
            array_push($this->openAPINullablesSetToNull, 'AutoGeneratedTextOptOut');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('AutoGeneratedTextOptOut', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['AutoGeneratedTextOptOut'] = $AutoGeneratedTextOptOut;

        return $this;
    }

    /**
     * Gets AutoGeneratedImageOptOut
     *
     * @return bool|null
     */
    public function getAutoGeneratedImageOptOut()
    {
        if (!isset($this->container['AutoGeneratedImageOptOut']) || is_null($this->container['AutoGeneratedImageOptOut'])) {
            return null;
        }
        return $this->container['AutoGeneratedImageOptOut'];
    }

    /**
     * Sets AutoGeneratedImageOptOut
     *
     * @param bool|null $AutoGeneratedImageOptOut AutoGeneratedImageOptOut
     *
     * @return self
     */
    public function setAutoGeneratedImageOptOut($AutoGeneratedImageOptOut)
    {
        if (is_null($AutoGeneratedImageOptOut)) {
            array_push($this->openAPINullablesSetToNull, 'AutoGeneratedImageOptOut');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('AutoGeneratedImageOptOut', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['AutoGeneratedImageOptOut'] = $AutoGeneratedImageOptOut;

        return $this;
    }

    /**
     * Gets SearchTermMatchingOptOut
     *
     * @return bool|null
     */
    public function getSearchTermMatchingOptOut()
    {
        if (!isset($this->container['SearchTermMatchingOptOut']) || is_null($this->container['SearchTermMatchingOptOut'])) {
            return null;
        }
        return $this->container['SearchTermMatchingOptOut'];
    }

    /**
     * Sets SearchTermMatchingOptOut
     *
     * @param bool|null $SearchTermMatchingOptOut SearchTermMatchingOptOut
     *
     * @return self
     */
    public function setSearchTermMatchingOptOut($SearchTermMatchingOptOut)
    {
        if (is_null($SearchTermMatchingOptOut)) {
            array_push($this->openAPINullablesSetToNull, 'SearchTermMatchingOptOut');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('SearchTermMatchingOptOut', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['SearchTermMatchingOptOut'] = $SearchTermMatchingOptOut;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
